### ISSUE TITLE
Envoi du PIN code par email

### ISSUE THREAD

**Issue by XCarrel** [CPNV-INFO/Sordela#2]
Lorsqu'une personne est ajoutée et que le champ de contact contient un numéro de portable valable, l'application envoie un email à xcl@cpnv.ch (temporaire), contenant le numéro de téléphone et le PIN code

**Comment by XCarrel** [comment]
Pour reconnaître un numéro de portable valable, on supprime tous les espaces et il ne doit rester qu'une chaîne de 10 caractères commençant par "07"

**Comment by NielsG98** [comment]
Le bouton d'envoi de code qui permet d'envoyer un SMS à l'utilisateur a été ajoutée. La fonction envoie un mail à <numero tel>@sms.admin.ch avec le code comme message. Bizarrement, j'ai essayé avec mon propre numéro et je n'ai reçu aucun SMS, même après plusieurs heures. J'ai pourtant vérifié l'adresse que je génère ainsi que le contenu. Le problème ne semble pas venir du code.
