### ISSUE TITLE
Procédure de démarrage

### ISSUE THREAD

**Issue by XCarrel** [CPNV-INFO/Sordela#4]
Etablir une procédure qui permet de démarrer l'application en mode 'kiosk' sur Chrome et en navigation privée.
Documenter dans le readme

**Comment by NielsG98** [comment]
Documentation créée dans le ReadMe. Mode kiosk dans Chrome ainsi qu'un script généré avec AutoHotKey à lancer, qui permet de bloquer certains raccourci, comme ALT-F4 ou CTRL-N.

Je n'ai pas trouvé de méthode pour bloquer les raccouris Windows comme Ctrl-Alt-Del et Ctrl-Shift-Esc qui fonctionnent. J'ai trouvé des scripts pour modifier le registre, mais cela ne semble pas marcher sous Windows 10/ au cpnv.
